# Generated by Django 5.2 on 2025-05-03 17:49

import django.contrib.auth.validators
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_following', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('followers', models.ManyToManyField(related_name='followers_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default=None, editable=False, max_length=250)),
                ('image', models.ImageField(default=None, editable=False, storage=django.core.files.storage.FileSystemStorage(location='/djangoproject/media'), upload_to='')),
                ('likedBy', models.ManyToManyField(related_name='posts_likes', to=settings.AUTH_USER_MODEL)),
                ('postedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts_postedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
