# Generated by Django 5.2 on 2025-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_posts_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="text",
            field=models.TextField(default=" ", editable=False, max_length=250),
        ),
    ]
