# Generated by Django 5.2 on 2025-05-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_posts_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Posts",
        ),
    ]
